---
title: "Data Scientist test"
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

This repository contains data and instructions for a test as part of you application

## The task

The task in this assessment is: 
___build the best model you can, predicting the 'Death' column, in this dataset.___

We will not restrict you to particular model classes, statistical paradigms, or sets of assumptions. 
Please consider the following:

+ Some exploratory analyses and visualisations of the data items
+ Statistical / machine learning models to predict the 'Death' field
+ A method of assessing how 'good' a model is, and how you select the 'best' model
+ Interpretation of the model outputs

We advise you to __spend no more than two hours on this test__, as it is only part of the selection process.  The first stage of interview will be to discuss you analysis approach, regardless of whether it 'worked,' so we ask you to leave any partial code/documents you create, even if they are incomplete.  This will allows us to see your thought process, as there are many ways to approach this exercise.

## Instructions 

To access the data and share your answers with us:

+ Download a copy of the data in this repository:
 + If you are familiar with GitHub, please clone the repository and push your work to your own repository.
 + If you are completely new to GitHub, you can download the data using the green 'Clone or download' button and send your answers by email to HED@uhb.nhs.uk.

Once you have downloaded the data/repository:

+ Load the `simulated_data.csv` file to your analysis environment of choice.  We encourage the use of `R` and `Rmarkdown` in particular, but are happy to assess most common analysis environments provided we can access them.


__Please submit you answers by  1700 BST, Monday 3rd August 2020__


If you have questions, or need further support, please contact HED@uhb.nhs.uk 